platform :ios, '12.4'

target 'AIropress' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'


  pod 'TinyConstraints'


  # Essential Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # Other Firebase products

  pod 'Firebase/Firestore'


  target 'AIropressTests' do
    inherit! :search_paths

    pod 'TinyConstraints'
  end

end
